### ISSUE TITLE
node-net-reconnect fails to install on node LTS version 10.16.3 or 12.16.2

### ISSUE THREAD

**Issue by huwylphi** [Cloud-Automation/node-net-reconnect#5]
it seems that building the dependency to _net-keepalive_ throws exceptions like
_../../nan/nan_object_wrap.h:24:25: error: ‘class Nan::Persistent<v8::Object>’ has no member named ‘IsNearDeath’_

**Comment by stefanpoeter** [comment]
I would say you should contact the guys from the net-keepalive module then.

**Comment by ceremcem** [comment]
This issue should be reopened and a proper workaround should be provided by this repo because a failing dependency is also a  first-class issue of the dependent project.

**Comment by ceremcem** [comment]
You are using [`net-keepalive: ^0.4.1`](https://github.com/Cloud-Automation/node-net-reconnect/blob/8a99a45df3caa986e52f00424a366c84a6ac4d73/package.json#L27) and current `net-keepalive` version is `1.3.2`. Please consider updating this dependency.

**Comment by stefanpoeter** [comment]
The branch dev/1.0 contains the required changes. Does not build on node v8 but does compile on node v12. Can you check if it builds on v10?

**Comment by ceremcem** [comment]
`dev/1.0` branch does not help: 

```
$ npm i --save Cloud-Automation/node-net-reconnect#dev/1.0

> ffi-napi@3.0.1 install /home/ceremcem/sync/curr-projects/aktos/scadajs-template/scada.js/lib/dcs/transports/tcp/node_modules/ffi-napi
> node-gyp-build

make: Entering directory '/home/ceremcem/sync/curr-projects/aktos/scadajs-template/scada.js/lib/dcs/transports/tcp/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  181 |    FFI_ASSERT (0);
      |                  ^
../deps/libffi/src/x86/ffi64.c:156:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
  156 |       {
      |       ^
../deps/libffi/src/x86/ffi64.c:183:5: note: here
  183 |     case FFI_TYPE_FLOAT:
      |     ^~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
make: g++: No such file or directory
make: *** [ffi_bindings.target.mk:124: Release/obj.target/ffi_bindings/src/ffi.o] Error 127
make: Leaving directory '/home/ceremcem/sync/curr-projects/aktos/scadajs-template/scada.js/lib/dcs/transports/tcp/node_modules/ffi-napi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 5.6.0-2-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ceremcem/sync/curr-projects/aktos/scadajs-template/scada.js/lib/dcs/transports/tcp/node_modules/ffi-napi
gyp ERR! node -v v12.18.2
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN tcp@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.0.1 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi-napi@3.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ceremcem/.npm/_logs/2020-07-13T16_40_45_033Z-debug.log
```

**Comment by yeongren** [comment]
@ceremcem  Did you manage to solve this?

**Comment by ceremcem** [comment]
It's been a long time, so I can't remember the exact details. However, my application works quite well, so I assume it's been fully resolved by [this](https://github.com/BinaryFissionGames/node-net-reconnect/commit/5b0a533d049c861bdac4a24cccb728bb0912aa2b#comments), so https://github.com/BinaryFissionGames/node-net-reconnect#master solved the issue.
